### ISSUE TITLE
Update for newest Altay version

### ISSUE THREAD

**Issue by Aenoxic** [tim03we/MyPlot-Altay#1]
Yea yea yea pleaseee tim. Goooo! :D

**Comment by lowingly** [comment]
+1 Altay1.9 pls~   QAQ

**Comment by tim03we** [comment]
what do you mean?

**Comment by lowingly** [comment]
That is mean...myplot does not work in altay1.9... and need your help...
![6kbaqxg4 fef0l z f9hva](https://user-images.githubusercontent.com/18659344/52911551-5a5a3580-3273-11e9-816d-41666df82ee0.png)

**Comment by Aenoxic** [comment]
Hate Altay at all.

**Comment by tim03we** [comment]
I'll take a look.

**Comment by lowingly** [comment]
I understand how you feel.
All of my plugins related to the world-generated/multi-world have collapsed in altay1.9.
Thanks tim03we.

**Comment by tim03we** [comment]
It works now again.

**Comment by lowingly** [comment]
There is still an error... It seems that there is an extra "->" in GenerateSubCommand.php (line 30)  if($sender->getServer()->->getLevelManager()->isLevelGenerated($levelName)) {
I removed one "->" myself, but I have a new error. . (Maybe I changed it wrong.)
![ty 2h6 x88lob1 i5a4 hzp](https://user-images.githubusercontent.com/18659344/52911937-701e2980-3278-11e9-996b-f7b731c6dd73.png)

I just want to cry :(

**Comment by tim03we** [comment]
Now!

**Comment by lowingly** [comment]
> Now!

GOOD!! work now!!Thanks!
